name: update IaSQL

on:
  workflow_dispatch:
    inputs:
      iasql_version:
        description: 'IaSQL released version'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update formulae
        run: ./update_iasql_formulae.sh ${{ github.event.inputs.iasql_version }}
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          message: Bump version ${{ github.event.inputs.iasql_version }}
